name: Docker CI/CD

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dev client image for tests
        run: docker build -t mrinal2100/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests in client
        run: docker run -e CI=true mrinal2100/react-test npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy from the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build production images
        run: |
          docker build -t mrinal2100/multi-client -f ./client/Dockerfile.prod ./client
          docker build -t mrinal2100/multi-nginx ./nginx
          docker build -t mrinal2100/multi-server -f ./server/Dockerfile.prod ./server
          docker build -t mrinal2100/multi-worker  -f ./client/Dockerfile.prod ./worker

      - name: Push images to Docker Hub
        run: |
          docker push mrinal2100/multi-client
          docker push mrinal2100/multi-nginx
          docker push mrinal2100/multi-server
          docker push mrinal2100/multi-worker
