name: Docker CI/CD
on:
  push:
    branches:
      - main  # or 'master' if that's your default branch
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  S3_BUCKET: elasticbeanstalk-us-east-1-610924852117
  APPLICATION_NAME: multi-docker
  ENVIRONMENT_NAME: MultiDocker-env
  BUCKET_PATH: docker-multi

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dev client image for tests
        run: docker build -t mrinal2100/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests in client
        run: docker run -e CI=true mrinal2100/react-test npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy from the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build production images
        run: |
          docker build -t mrinal2100/multi-client -f ./client/Dockerfile.prod ./client
          docker build -t mrinal2100/multi-nginx -f ./nginx/Dockerfile.prod ./nginx
          docker build -t mrinal2100/multi-server -f ./server/Dockerfile.prod ./server
          docker build -t mrinal2100/multi-worker  -f ./worker/Dockerfile.prod ./worker

      - name: Push images to Docker Hub
        run: |
          docker push mrinal2100/multi-client
          docker push mrinal2100/multi-nginx
          docker push mrinal2100/multi-server
          docker push mrinal2100/multi-worker
      - name: Install AWS CLI
        uses: aws-actions/aws-cli@v1

      - name: Zip Dockerrun.aws.json
        run: zip -r deploy.zip Dockerrun.aws.json .ebextensions

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://$S3_BUCKET/$BUCKET_PATH/${{ github.sha }}.zip

      - name: Deploy to Elastic Beanstalk
        uses: mrinal2100/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ env.APPLICATION_NAME }}
          environment_name: ${{ env.ENVIRONMENT_NAME }}
          region: ${{ env.AWS_REGION }}
          version_label: ${{ github.sha }}
          bucket_name: ${{ env.S3_BUCKET }}
          bucket_key: ${{ env.BUCKET_PATH }}/${{ github.sha }}.zip
